version: "3.9"

services:
  postgres-meuapp:
      image: postgres:15-alpine
      container_name: meuapp-db

      environment:
        POSTGRES_USER_FILE: /run/secrets/pg_user 
        POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
        POSTGRES_DB_FILE: /run/secrets/pg_db
        
        TZ: America/Sao_Paulo
        
      ports:
        - "5432:5432"

      volumes:
        - postgres_data:/var/lib/postgresql/data
        
        - ./init-scripts:/docker-entrypoint-initdb.d

        - ./secrets/pg_user.txt:/run/secrets/pg_user:ro
        - ./secrets/pg_password.txt:/run/secrets/pg_password:ro
        - ./secrets/pg_db.txt:/run/secrets/pg_db:ro

      restart: always

  tomcat-meuapp:
    container_name: meuapp-api

    build:
      context: . 
      dockerfile: Dockerfile
    
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: dev 
    
    ports:
      - "8080:8080"

    volumes:
      - ./secrets/pg_user.txt:/run/secrets/pg_user:ro
      - ./secrets/pg_password.txt:/run/secrets/pg_password:ro
      - ./secrets/pg_db.txt:/run/secrets/pg_db:ro
      - ./secrets/jwt_key.properties:/run/secrets/jwt_key:ro
    depends_on:
      - postgres-meuapp
    
    restart: always	  

volumes:
  postgres_data:
