version: "3.9"

services:
  postgres_meuapp:

      environment:
        POSTGRES_USER_FILE: 
        POSTGRES_PASSWORD_FILE: 
        POSTGRES_DB_FILE: 
        
      ports: []
        
      volumes:
        - ./init-scripts:/docker-entrypoint-initdb.d

  tomcat-meuapp:
  	volumes: []
    
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate # Cuidado: Mude para 'validate' em produção
      # Adicionando o hostname do DB, necessário para o entrypoint montar a URL
	  SPRING_PROFILES_ACTIVE: prod # Define o perfil DEV
    
    ports: []

volumes:
  postgres_data:
